"""
Transcription formatting utility.

This script processes a raw transcription file (`transcriptions.txt`) generated by the
application, extracting user (Interviewee) and model (Interviewer) dialogue turns
from JSON payloads and formatting them into a readable text file (`final_transcription.txt`).
"""

import json

def format_transcriptions(input_file="transcriptions.txt", output_file="final_transcription.txt"):
    """
    Reads a raw transcription file and writes a formatted conversation log.

    Args:
        input_file (str): Path to the raw transcriptions file. Defaults to "transcriptions.txt".
        output_file (str): Path to the output file. Defaults to "final_transcription.txt".
    """
    try:
        with open(input_file, "r", encoding="utf-8") as f:
            lines = f.readlines()

        final_transcription = ""

        is_output = False
        is_input = False

        for line in lines:
            if "OUTPUT: " in line:
                if not is_output:
                    is_output = True
                    is_input = False
                    final_transcription += "\n[Interviewer]: "
                json_str = line.split("OUTPUT: ")[1].strip()
                try:
                    data = json.loads(json_str)
                    text = data.get("text")
                    if text:
                        final_transcription += text
                except json.JSONDecodeError as e:
                    print(f"Error decoding JSON: {e}")
                    # print(f"Original string: {json_str}")
            if "INPUT: " in line:
                if not is_input:
                    is_output = False
                    is_input = True
                    final_transcription += "\n[Interviewee]: "
                json_str = line.split("INPUT: ")[1].strip()
                try:
                    data = json.loads(json_str)
                    text = data.get("text")
                    if text:
                        final_transcription += text
                except json.JSONDecodeError as e:
                    print(f"Error decoding JSON: {e}")
                    # print(f"Original string: {json_str}")

        with open(output_file, "w", encoding="utf-8") as out_f:
            out_f.write(final_transcription.strip())

        print(f"Successfully formatted transcription to {output_file}")

    except FileNotFoundError:
        print(f"Input file {input_file} not found.")
    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    format_transcriptions()
